<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFrameworks>net10.0-windows;net472</TargetFrameworks>
		<UseWPF>true</UseWPF>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>AppleTvControlLibrary.Remote.Mrp.Wpf</RootNamespace>
		<AssemblyName>AppleTv.Remote.Mrp.Wpf</AssemblyName>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Debug'">
		<DebugType>portable</DebugType>
		<DebugSymbols>true</DebugSymbols>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
	</PropertyGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net472'">
		<PackageReference Include="IsExternalInit" Version="1.0.3">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Hafner.Compatibility.MetaPackage" Version="1.9.0" />
		<PackageReference Include="System.Memory" Version="4.6.3" />
		<PackageReference Include="System.Text.Json" Version="10.0.11" />
		<Reference Include="System.Net.Http" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Microsoft.Bcl.Memory" Version="10.0.11" />
	</ItemGroup>

	<ItemGroup>
	  <Page Include="App.xaml" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\AppleTv.Mrp\AppleTv.Mrp.csproj" />
		<ProjectReference Include="..\AppleTV.Companion.Discovery\AppleTV.Companion.Discovery.csproj" />
		<ProjectReference Include="..\AppleTv.Hap\AppleTv.Hap.csproj" />
	</ItemGroup>

</Project>
