<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<LangVersion>13.0</LangVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>AppleTvControlLibrary.Remote.Wpf</RootNamespace>
		<AssemblyName>AppleTv.Remote.Wpf</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
	  <Page Include="App.xaml" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\AppleTV.Companion\AppleTV.Companion.csproj" />
		<ProjectReference Include="..\AppleTV.Companion.Discovery\AppleTV.Companion.Discovery.csproj" />
	</ItemGroup>

</Project>
