<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<RootNamespace>AppleTvControlLibrary.Mrp.FakeDevice</RootNamespace>
		<AssemblyName>AppleTv.Mrp.FakeDevice</AssemblyName>
		<TargetFrameworks>net10.0;net472</TargetFrameworks>
		<LangVersion>13.0</LangVersion>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BouncyCastle.Cryptography" Version="2.7.0" />
		<PackageReference Include="Microsoft.Bcl.Memory" Version="10.0.11" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net472'">
		<PackageReference Include="IsExternalInit" Version="1.0.3">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="System.Memory" Version="4.6.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\AppleTv.Mrp\AppleTv.Mrp.csproj" />
		<ProjectReference Include="..\..\src\AppleTv.Hap\AppleTv.Hap.csproj" />
	</ItemGroup>

</Project>
